export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: { Row: { id: string; full_name: string | null; role: "admin"; created_at: string; updated_at: string }; Insert: { id: string; full_name?: string | null; role: "admin"; created_at?: string; updated_at?: string }; Update: { full_name?: string | null; role?: "admin"; updated_at?: string }; Relationships: [] };
      events: { Row: { id: string; name: string; slug: string; invitation_image_path: string; loading_image_path: string | null; event_date: string; rsvp_deadline: string | null; loading_duration_ms: number; is_published: boolean; public_landing_enabled: boolean; landing_heading: string | null; landing_celebrant_name: string; landing_banner_image_path: string | null; landing_crown_image_path: string | null; landing_celebrant_image_path: string | null; landing_description: string | null; landing_details: string | null; landing_music_url: string | null; landing_music_autoplay: boolean; landing_rsvp_cta_text: string; created_by: string; created_at: string; updated_at: string }; Insert: { id?: string; name: string; slug: string; invitation_image_path: string; loading_image_path?: string | null; event_date: string; rsvp_deadline?: string | null; loading_duration_ms?: number; is_published?: boolean; public_landing_enabled?: boolean; landing_heading?: string | null; landing_celebrant_name?: string; landing_banner_image_path?: string | null; landing_crown_image_path?: string | null; landing_celebrant_image_path?: string | null; landing_description?: string | null; landing_details?: string | null; landing_music_url?: string | null; landing_music_autoplay?: boolean; landing_rsvp_cta_text?: string; created_by: string; created_at?: string; updated_at?: string }; Update: Partial<Database["public"]["Tables"]["events"]["Insert"]>; Relationships: [] };
      invitations: { Row: { id: string; event_id: string; label: string; public_slug: string; max_extra_guests: number; internal_notes: string | null; is_active: boolean; archived_at: string | null; created_by: string; created_at: string; updated_at: string }; Insert: { id?: string; event_id: string; label: string; public_slug: string; max_extra_guests?: number; internal_notes?: string | null; is_active?: boolean; archived_at?: string | null; created_by: string; created_at?: string; updated_at?: string }; Update: Partial<Database["public"]["Tables"]["invitations"]["Insert"]>; Relationships: [] };
      invitation_guests: { Row: { id: string; invitation_id: string; full_name: string; is_primary: boolean; sort_order: number; created_at: string; updated_at: string }; Insert: { id?: string; invitation_id: string; full_name: string; is_primary?: boolean; sort_order?: number; created_at?: string; updated_at?: string }; Update: Partial<Database["public"]["Tables"]["invitation_guests"]["Insert"]>; Relationships: [] };
      rsvps: { Row: { id: string; invitation_id: string; response: "attending" | "not_attending"; named_guests_attending: number; extra_guests_attending: number; message: string | null; responded_at: string; updated_at: string }; Insert: { id?: string; invitation_id: string; response: "attending" | "not_attending"; named_guests_attending?: number; extra_guests_attending?: number; message?: string | null; responded_at?: string; updated_at?: string }; Update: Partial<Database["public"]["Tables"]["rsvps"]["Insert"]>; Relationships: [] };
      landing_rsvp_submissions: { Row: { id: string; event_id: string; first_name: string; last_name: string; response: "attending" | "not_attending"; created_at: string }; Insert: { id?: string; event_id: string; first_name: string; last_name: string; response: "attending" | "not_attending"; created_at?: string }; Update: Partial<Database["public"]["Tables"]["landing_rsvp_submissions"]["Insert"]>; Relationships: [] };
    };
    Views: Record<string, never>;
    Functions: {
      create_invitation_with_guests: { Args: { p_event_id: string; p_label: string; p_public_slug: string; p_max_extra_guests: number; p_internal_notes: string; p_guests: Json }; Returns: string };
      update_invitation_with_guests: { Args: { p_invitation_id: string; p_label: string; p_public_slug: string; p_max_extra_guests: number; p_internal_notes: string; p_guests: Json }; Returns: undefined };
    };
    Enums: { app_role: "admin"; rsvp_response: "attending" | "not_attending" };
    CompositeTypes: Record<string, never>;
  };
};
